name: ShellCheck

on:
  push:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script:
          #- ./bin/smoke_test.sh
          - ./bin/probes/internal/env_probe
          #- ./bin/host_capabilities.sh 
    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Check script
        run: shellcheck "${{ matrix.script }}"